-- CREACIÓN DE LA BASE DE DATOS
CREATE DATABASE Neoplastic;
GO
USE Neoplastic;
GO

-- TABLA USUARIO
CREATE TABLE Usuario (
    UsuarioID INT IDENTITY(1,1) PRIMARY KEY,
    Nombre NVARCHAR(100) NOT NULL,
    Correo NVARCHAR(100) UNIQUE NOT NULL,
    Password NVARCHAR(255) NOT NULL,
    Rol NVARCHAR(50) NOT NULL CHECK (Rol IN ('Operador', 'Administrador'))
);

-- TABLA MARCA
CREATE TABLE Marca (
    MarcaID INT IDENTITY(1,1) PRIMARY KEY,
    Nombre NVARCHAR(100) NOT NULL
);

-- TABLA CLASIFICACIÓN
CREATE TABLE Clasificacion (
    ClasificacionID INT IDENTITY(1,1) PRIMARY KEY,
    Tipo NVARCHAR(50) NOT NULL
);

-- TABLA PRODUCTO
CREATE TABLE Producto (
    ProductoID INT IDENTITY(1,1) PRIMARY KEY,
    Nombre NVARCHAR(100) NOT NULL,
    MarcaID INT NOT NULL,
    ClasificacionID INT NOT NULL,
    FOREIGN KEY (MarcaID) REFERENCES Marca(MarcaID),
    FOREIGN KEY (ClasificacionID) REFERENCES Clasificacion(ClasificacionID)
);

-- TABLA PRECIO
CREATE TABLE Precio (
    PrecioID INT IDENTITY(1,1) PRIMARY KEY,
    Monto DECIMAL(10,2) NOT NULL CHECK (Monto > 0),
    ProductoID INT NOT NULL UNIQUE,
    FOREIGN KEY (ProductoID) REFERENCES Producto(ProductoID)
);

-- TABLA CLIENTE
CREATE TABLE Cliente (
    ClienteID INT IDENTITY(1,1) PRIMARY KEY,
    Nombre NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) UNIQUE NOT NULL,
    Telefono NVARCHAR(20) NOT NULL
);
--TABLA VENTA 
CREATE TABLE Venta (
VentaID INT IDENTITY(1,1) PRIMARY KEY
IdCliente INT NOT NULL,
FechaVenta DATETIME DEFAULT GETDATE(),
Total Decimal (10,2) NOT NULL,
PrecioID INT NOT NULL UNIQUE,
    FOREIGN KEY (PrecioID) REFERENCES Precio(PrecioID)
    );

